### ISSUE TITLE
Suggestion: Remove table names from column names

### ISSUE THREAD

**Issue by jake-nz** [amds-ldeo/ada-db-spec#1]
There are some columns that contain the table name, which is probably unnecessary.
I'd like to suggest the following columns be renamed.

* `external_identifier_schemes/scheme_name` → `external_identifier_schemes/name`
* `subject_scheme_descriptions/scheme_url` → `subject_scheme_descriptions/url`
* `subject_scheme_descriptions/scheme_description` → `subject_scheme_descriptions/description`
* `file_extensions/file_extension` → `file_extensions/extension`
* `file_extensions/file_type_name` → `file_extensions/type_name`
* `funders/funder_abbrev` → `funders/abbreviation`
* `funders/funder_name` → `funders/name`
* `funders/funder_url` → `funders/url`
* `licenses/license_abbrev` → `licenses/abbreviation`
* `licenses/license_name` → `licenses/name`
* `licenses/license_url` → `licenses/url`
* `name_entity_identifiers/name_identifier_value` → `name_entity_identifiers/identifier`
* `record_files/file_name` → `record_files/name`
* `record_files/file_checksum` → `record_files/checksum`
* `record_files/file_size_bytes` → `frecord_files/size_bytes`
* `records/record_doi` → `records/doi`
* `subject_schemes/subject_scheme_template` → `subject_schemes/template`
* `subject_schemes/subject_scheme_description` → `subject_schemes/description`

**Comment by sparkji** [comment]
Naming convention for column name({table_name}_?) came from our legacy database. The reason is that it is easy for non-tech staff who need to access the database directly to understand the db without confusion. But I totally agree with your suggestions, will change them.

**Comment by sparkji** [comment]
fixed
