### ISSUE TITLE
Suggestion: Unabbreviate column names

### ISSUE THREAD

**Issue by jake-nz** [amds-ldeo/ada-db-spec#2]
There are a few column names that are abbreviated. For consistency, I'd like to suggest the following columns be renamed.

* `file_extensions/desc_url` → `file_extensions/description_url`
* `funders/funder_abbrev` → `funders/abbreviation`
* `licenses/license_abbrev` → `licenses/abbreviation`
* `funders/award_num` → `funders/award_number`

**Comment by sparkji** [comment]
Thanks for suggestion, will update.

**Comment by sparkji** [comment]
fixed
