### ISSUE TITLE
Are `created_at` & `updated_at` needed in `record_trails`

### ISSUE THREAD

**Issue by jake-nz** [amds-ldeo/ada-db-spec#3]
`record_trails` is automatically populated when a record status changes and has `status_on`.
That means `created_at` and `updated_at` are probably not useful in this table. All three dates will always be the same.

**Comment by jake-nz** [comment]
@sparkji, @davestern tagging you for visibility. I can't assign people to these issues.

**Comment by sparkji** [comment]
@jake-nz, @davestern Yes, they are not useful for record_trails, I'll delete them.

**Comment by sparkji** [comment]
fixed
